spring:
  application:
    name: reservation
  datasource:
    url: "jdbc:h2:mem:testdb"
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

fonoapi:
  baseurl: "https://fonoapi.freshpixl.com/"
  token: "12345"
  corn: "0 0 0 * * *"
